---
version: '3'

services:
  rna-seq-pipeline:
    container_name: rna-seq-pipeline
    build:
      context: build
      args:
        http_proxy: ${http_proxy}
    image: dceoy/rna-seq-pipeline:latest
    user: ${UID}:${GID}
    userns_mode: host
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - .:/wd:ro
      - ./bin:/opt/bin
      - ./output:/out
    working_dir: /wd
    entrypoint:
      - /opt/bin/workflow.sh
    command:
      - --qc
      - --ref-gtf=/wd/ref/GCF_000001405.38_GRCh38.p12_genomic.gtf.gz
      - --ref-fna=/wd/ref/GCF_000001405.38_GRCh38.p12_genomic.fna.gz
      - --in-dir=/wd/in
      - --out-dir=/out
